### ISSUE TITLE
email address wrong

### ISSUE THREAD

**Issue by pcav** [guilhermehrn/spugeomemorial#2]
Delivery has failed to these recipients or groups:

guilherme.henrique@planejamento.gov.br
The email address you entered couldn't be found. Please check the reciDelivery has failed to these recipients or groups:

guilherme.henrique@planejamento.gov.br
The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your helpdesk.

pient's email address and try to resend the message. If the problem continues, please contact your helpdesk.

**Comment by guilhermehrn** [comment]
Sorry!
I'll correct.

**Comment by guilhermehrn** [comment]
I fixed the email in the metadata file. Really the email was wrong.

I updated the version 0.3 of the plugin.

Please approve the plugin as it is very important for the Brazilian Government and it is still under development and evolution.

**Comment by pcav** [comment]
Thanks. Now approving, but please fix also the home page as soon as possible, see other ticket.
Cheers.
