### ISSUE TITLE
Cópia de repositório

### ISSUE THREAD

**Issue by lcoandrade** [guilhermehrn/spugeomemorial#3]
Sei que trabalhamos com OpenSource, mas a ética deve estar sempre presente. Copiar um repositório e colocar o seu nome não é ético, é plágio. Vou entrar em contato com a SPU para tratar do assunto. Recomendo fazer um PR no meu repositório. Poderíamos pensar em criar templates para diversos órgãos, deixando um genérico para Pessoas Físicas.

No mínimo, vc deveria criar um Fork com o devido reconhecimento de autoria.

**Comment by guilhermehrn** [comment]
Olá, tudo bem?
Quando eu entrei na SPU, os funcionários usavam o complemento que você criou em atividades de geração de memoriais descritivos. Entretanto, o seu plugin tinha algumas limitações e não atendia a algumas regras de negócio da SPU, exigindo algumas modificações posteriores da resposta do programa.

Então eles me solicitaram para que eu modifica-se o programa para que a saída dele gerasse  respostas de acordo com os formatos adotados na SPU. Em seguida eu fiz um fork do seu projeto e modifiquei ele para atender as especificidades somente da SPU.

Depois que o programa foi testado internamente e aprovado eu subi ele no repositório do QGIS.  Pois era a maneira mais fácil de disponibilizar ele para as SPU’s dos outros estados. Além disso se você olhar na descrição do plugin [1] no Qgis eu deixo bem claro que é uma versão modificada do seu plugin.

Porem, devido a uma falha minha acabei não adicionando um readme aqui no repositório do GitHub explicitando a referência. Entretanto eu não tirei o seu nome dos cabeçalho das classes que você escreveu. As classes que estão com o meu nome são classes que são geradas automaticamente do plugin Build do Qgis.

Outro ponto é que você deixa claro nesses cabeçalhos que você colocou sob a licença GNU,  além disso você colocou eu um repositório aberto. Ao fazer isso, automaticamente você concedeu a qualquer um pegar o seu código, modificá-lo e redistribuir [2] sobre a mesma licença. 

O meu código possui modificações feitas especialmente para as regras de negócio da SPU, por isso eu não dei Pull Request em seu projeto, pois eram modificações muito específicas. O que poderia atrapalhar a generalidade do seu código.

Em todo o momento, tanto dentro da SPU quanto dentro da comunidade do QGIS eu deixei claro que o meu código é uma versão modificada do seu plugin. E a meu ver não faltei com ética deixando de citar qual foi a gêneses do meu código. E muito menos desrespeitei qualquer termo da Licença GNU ao qual você colocou o seu código.

[1] https://plugins.qgis.org/plugins/spugeomemorial/
[2] https://www.gnu.org/philosophy/philosophy.html

**Comment by lcoandrade** [comment]
Pra começar, GNU é um sistema operacional. Vc está se referindo à licença GPL e eu conheço a filosofia dela.

Bem, vi a apresentação do plugin no FOSS4.GIS.GOV 2018 (infelizmente eu não estava presente no momento, mas alguns militares que trabalhavam comigo estavam). Em nenhum momento meu nome é mencionado, como vc pode ver no slide apresentado no evento. 
<img width="627" alt="Captura de Tela 2020-06-17 às 20 26 57" src="https://user-images.githubusercontent.com/8769816/84960797-f77fe500-b0d8-11ea-851a-f59b9d74db9e.png">

Só se ouve (mais de uma vez) que Guilherme Henrique Rodrigues Nascimento era o desenvolvedor. Fato que, também, se comprova no vídeo que está no YouTube (https://www.youtube.com/watch?v=lrUJaV2zFBI&t=17s).

Posso estar enganado, mas isso me parece má fé. Não é pq um código é GPL que posso assumir autoria.

**Comment by lcoandrade** [comment]
Como falei antes, já que as mudanças são estéticas, vc poderia fazer um PR para adicionar os estilos da SPU no plugin original. Seria até melhor. Poderia haver templates para diversos órgãos (fazendo um seletor), deixando um genérico para Pessoas Físicas (original).

**Comment by guilhermehrn** [comment]
Vamos lá;
 1) Existe o SO GNU, mas também existe A Licença Pública Geral GNU (GNU General Public License) que é frequentemente chamada abreviadamente de GNU GPL. No meu textão eu abreviei ainda mais para simplesmente GNU. No link que eu te mandei tem explicando tudo inclusive sobre as licenças. (podemos discutir melhor sobre isso em outro canal de comunicação)

2) Quanto aos Slides e apresentações não foi eu quem fiz. O meu papel foi única e exclusivamente com os código dos programa. 

3) Em nenhum momento foi um ato de má fé, pois como eu já falei no código do repositório tem o seu nome nas classes que você fez, em nenhum momento fiz questão de retira-lo, pois justamente foi a forma que eu encontrei de referenciar seu trabalho.

4) Eu tenho plena certeza que não foi por ma fé da palestrante, em não ter citado o seu nome. Podem existir n motivos pelos quais a palestrante não citou que o projeto surgiu a partir do seu, e que podem incluir desde uma falha na oratória dela até um simples erro na construção dos slides.

5) Além disso, Citei sobre o seu projeto na descrição do plugin lá no repositório do QGIS. Se foi você que desenvolveu, automaticamente quem procurar pelo seu projeto a partir do meu no repositório vai chegar até você.

7) Por outro lado compreendo o seu ponto de vista, pois você se sentiu constrangido com com vídeo apresentado uma versão modificada do seu programa sem referencia-lo.

**Comment by guilhermehrn** [comment]
Qualquer coisa deixo aqui o meu email para podermos discutir melhor essa questão e esclarecermos ela: guilherme.henrique.nasc@gmail.com
